name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build Extension
        run: pnpm build

      - name: Package Extension
        run: pnpm package

      - name: Rename Package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          VERSION_FILENAME=$(echo $VERSION | tr '.' '-')
          mv build/chrome-mv3-prod.zip build/kaibola-${VERSION_FILENAME}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/kaibola-*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
